### ISSUE TITLE
Unable to install with Bower

### ISSUE THREAD

**Issue by pribilinskiy** [fyneworks/star-rating#11]
The package is not registered in Bower registry and it's name is conflicting with *star-rating* from *cmartinezv* https://github.com/cmartinezv/star-rating/blob/master/bower.json

Also I couldn't install with `bower install fyneworks/star-rating` and `bower install git://github.com/fyneworks/star-rating`, in both cases there's an error:
```
bower star-rating#*            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/fyneworks/star-rating.git=git://github.com/fyneworks/star-rating.git", exit code of #128

Additional error details:
fatal: remote error: 
  fyneworks/star-rating.git=git://github.com/fyneworks/star-rating is not a valid repository name
```

**Comment by fyneworks** [comment]
There are a lot of jquery star rating plugins out there, it was difficult to find a name that wasnt taken, but I've properly registered with bower now, package id "fyneworks-jquery-star-rating".

If you have any more suggestions I'll be happy to implement them!

**Comment by fyneworks** [comment]
Having trouble with bower actually. I've changed the version number to 4.11.0 but it doesn't seem to be working... can you help? What am I missing?

![image](https://cloud.githubusercontent.com/assets/3658719/6781065/75adb774-d162-11e4-8396-f7764c3c930f.png)

**Comment by fyneworks** [comment]
Scrap that guys. Added git tag 4.11.0 and we're up and running.
`bower install fyneworks-jquery-star-rating` FTW!
