### ISSUE TITLE
Comparison with similar libraries

### ISSUE THREAD

**Issue by dandv** [fyneworks/star-rating#15]
How does this plugin differ from @kartik-v's [bootstrap-star-rating](https://github.com/kartik-v/bootstrap-star-rating), which is more popular and actively maintained?

**Comment by digggggggggg** [comment]
You answered your own question right? It's less popular and less actively maintained! Haha. Just kidding. 

I stopped working on this plugin a long time ago when there seemed to be much better competing plugins out there. (way before the one you mentioned came to be). 

At first glance I would say they're completely different. But 2 things are obvious: the other plugin needs bootstrap, this doesn't (that may be desirable if you can't or don't want to use bootstrap) and the other plugin uses a single input, this uses radio boxes (which may be desirable). 

But is there any particular reason you ask? If you give me some background I might be able to be more specific about the differences.

**Comment by digggggggggg** [comment]
Also, it uses glyphs instead of images which is way better. It has more comprehensive options, which is never a bad thing. A better api. Better event handling. And is just as flexible because the underlying logic is very similar (you define min, max, step and the plugin creates a control on the fly). 

bootstrap star-rating wins, no contest!

**Comment by dandv** [comment]
> the other plugin needs bootstrap

From the [bootstrap-star-rating](https://github.com/kartik-v/bootstrap-star-rating) README:

_"The plugin uses Bootstrap markup and styling by default, but it can be overridden with any other CSS markup."_

> it uses glyphs instead of images which is way better

Does [bootstrap-star-rating](https://github.com/kartik-v/bootstrap-star-rating) use any images but [the loader](https://github.com/kartik-v/bootstrap-star-rating/tree/master/img)?

From the README again: 

_"Involves pure CSS3 styling of the stars. Say goodbye to image sprites or playing with image backgrounds. Offers clean scalable vector icons for consistent display across devices. Optionally one can use the Unicode character set to override symbols."_

**Comment by dandv** [comment]
> bootstrap star-rating wins, no contest!

Thank you! Appreciate the honesty.

**Comment by digggggggggg** [comment]
You are most welcome! :-)
